name: Cypress Tests
on:
  pull_request:
    branches:
      # - main
      - not-a-real-branch
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ralphie
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5434:5432
    env:
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      DATABASE_URL: postgres://postgres:ralphie@localhost:5434/postgres
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup code
        run: yarn

      - name: Migrate db.
        run: yarn migrate

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/automated/**/*
          build: yarn build
          start: yarn start
